// src/components/PageCard.tsx
import Image from 'next/image'
import profileImage from '../../public/vivanov.jpg'
import telegram from '../../public/telegram.svg'
import mail from '../../public/mail.svg'
import instagram from '../../public/instagram.svg'
import github from '../../public/github.svg'
import sun from '../../public/sun.svg'
import moon from '../../public/moon.svg'
import styled from 'styled-components'
import { useDispatch, useSelector } from 'react-redux'
import { setTheme, getThemeState } from '../store/themeSlice'
import { useEffect } from 'react'
import { useDarkMode } from 'use-dark-mode-ts'

const Card = styled.div`
  display: flex;
  position: relative;
  flex-direction: column;
  gap: 20px;
  vertical-align: top;
  margin: 0 auto;
  width: 290px;
  @media (max-width: 1059px) {
    width: 100%;
    max-width: 720px;
    justify-content: space-between;
    flex-direction: row;
    padding: 0 10px;
    gap: 10px;
  }
  @media (max-width: 499px) {
    padding: 0;
  }
`

const ImageWrapper = styled.div`
  display: flex;
  position: fixed;
  flex: 0 0 40px;
  width: 290px;
  height: 290px;
  img {
    border-radius: 50%;
  }
  @media (max-width: 1059px) {
    position: relative;
    width: 40px;
    height: 40px;
  }
`

const Social = styled.div`
  display: flex;
  position: fixed;
  top: 350px;
  width: 290px;
  justify-content: space-between;
  list-style: none;
  @media (max-width: 1059px) {
    position: static;
    width: 200px;
  }
`

const SocialItem = styled.a`
  display: inline-block;
  width: 60px;
  height: 60px;
  transition: opacity 0.6s;
  background-size: cover;
  background-repeat: no-repeat;
  border-radius: 30px;
  &:hover, &:focus, &:active {
    opacity: 0.5;
  }
  @media (max-width: 1059px) {
    width: 40px;
    height: 40px;
  }
`

const ThemeToggler = styled.button`
  position: absolute;
  top: 0;
  right: 0;
  width: 30px;
  height: 30px;
  border: none;
  background: none;
  background-size: cover;
  background-repeat: no-repeat;
  -webkit-appearance: none;
  -moz-appearance: none;
  z-index: 1;
  cursor: pointer;
  @media (max-width: 1059px) {
    width: 40px;
    height: 40px;
    right: -50px;
  }
`

const PageCard = () => {
  const isDarkMode = useDarkMode()
  const dispatch = useDispatch()
  const { theme } = useSelector(getThemeState)
  const links = [
    {
      title: 'Telegram',
      image: telegram,
      url: 'https://t.me/brightsdays',
      target: '_blank'
    },
    {
      title: 'Google Mail',
      image: mail,
      url: 'mailto:brightsdayss@mail.com',
      target: ''
    },
    {
      title: 'Instagram',
      image: instagram,
      url: 'https://www.instagram.com/brightsdays',
      target: '_blank'
    },
    {
      title: 'Github',
      image: github,
      url: 'https://github.com/BrightsDays',
      target: '_blank'
    }
  ]

  useEffect(() => {
    const localTheme = localStorage.getItem('bd-theme')

    if (localTheme) {
      localTheme === 'light' ? dispatch(setTheme('light')) : dispatch(setTheme('dark'))
    } else {
      !isDarkMode ? dispatch(setTheme('light')) : dispatch(setTheme('dark'))
    }
  }, [dispatch, isDarkMode])
  
  const onClick = () => {
    localStorage.setItem('bd-theme', theme === 'dark' ? 'light' : 'dark')
    dispatch(setTheme(theme === 'dark' ? 'light' : 'dark'))
  }

  const linkList = links.map((link, index) =>
    <SocialItem
      key={`url_${index}`}
      href={link.url}
      title={link.title}
      target={link.target}
      style={{ backgroundImage: `url(${link.image.src})` }}
    />
  )

  const togglerImage = theme === 'dark'
    ? sun
    : moon

  return (
    <Card>
      <ImageWrapper>
        <ThemeToggler
          style={{ backgroundImage: `url(${togglerImage.src})` }}
          onClick={onClick}
        />
        <Image
          src={profileImage}
          alt="vivanov"
        />
      </ImageWrapper>
      <Social>
        { linkList }
      </Social>
    </Card>
  )
}

export default PageCard

// src/components/PageCard.vue
<template>
  <div class="card">
    <input class="card__toggle"
           type="checkbox"
           v-model="darkTheme">
    <img class="card__image" src="../assets/img/card/vivanov.jpg" alt="vivanov" />
    <div class="card__social">
      <a class="card__link"
         v-for="(item, i) in links"
         :key="i"
         :class="`card__link--${item.class}`"
         :title="item.title"
         :href="item.url"
         :target="item.target" />
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      links: [
        { title: 'Telegram',
          class: 'telegram',
          url: 'https://t.me/brightsdays',
          target: '_blank'
        },
        { title: 'Google Mail',
          class: 'mail',
          url: 'mailto:brightsdayss@gmail.com',
          target: ''
        },
        { title: 'Instagram',
          class: 'instagram',
          url: 'https://instagram.com/brightsdays',
          target: '_blank'
        },
        { title: 'Github',
          class: 'github',
          url: 'https://github.com/BrightsDays',
          target: '_blank'
        }
      ],
      darkTheme: false
    }
  },
  mounted() {
    if (localStorage.theme === 'dark') this.darkTheme = true;
  },
  watch: {
    darkTheme() {
      if (this.darkTheme) {
        document.documentElement.setAttribute('theme', 'dark');
        localStorage.setItem('theme', 'dark');
      } else {
        document.documentElement.setAttribute('theme', 'light');
        localStorage.setItem('theme', 'light');
      }
    }
  }
}
</script>

<style lang="sass">
.card
  position: relative
  vertical-align: top
  margin: 0 auto
  width: 290px

  &__toggle
    position: absolute
    top: 0
    right: 0
    -webkit-appearance: none
    -moz-appearance: none
    border: none
    background: none
    width: 36px
    height: 20px
    cursor: pointer

    &:before
      content: ''
      position: absolute
      top: 0
      right: 0
      width: 44px
      height: 28px
      border: solid darkgrey 1px
      border-radius: 20px
      opacity: 1

    &:after
      content: url("../assets/img/card/color-mode.svg")
      position: absolute
      top: 3px
      right: 3px
      width: 24px
      height: 24px
      border-radius: 16px
      -moz-transition: all 0.3s ease-out
      -o-transition: all 0.3s ease-out
      -webkit-transition: all 0.3s ease-out
      transition: all 0.3s ease-out
      pointer-events: none

    &:checked.card__toggle:after
      transform: translateX(-16px)

  &__image
    display: block
    width: 290px
    height: 290px
    border-radius: 50%

  &__social
    display: flex
    justify-content: space-between
    list-style: none

  &__link
    display: inline-block
    width: 60px
    height: 60px
    transition: opacity 0.6s
    border-radius: 30px
    margin: 12px 0 0 0

    &--telegram
      background: url("../assets/img/card/telegram.svg") no-repeat

    &--twitter
      background: url("../assets/img/card/twitter.svg") no-repeat

    &--mail
      background: url("../assets/img/card/mail.svg") no-repeat

    &--instagram
      background: url("../assets/img/card/instagram.svg") no-repeat

    &--github
      background: url("../assets/img/card/github.svg") no-repeat

    &:hover, &:focus, &:active
      opacity: 0.5
</style>
